"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 16:45:30.627186
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('discovered_accounts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_connections'))
    )
    with op.batch_alter_table('ad_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_connections_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_connections_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('api_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('operations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_usage')),
    sa.UniqueConstraint('provider', 'day', name=op.f('uq_api_usage_provider_day'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('occurred_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('locked_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_jobs_dedupe_key'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('oauth_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nonce_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_code_verifier', sa.Text(), nullable=True),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states')),
    sa.UniqueConstraint('nonce_hash', name=op.f('uq_oauth_states_nonce_hash'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('ad_account_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('reverts_execution_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('provider_cache',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_provider_cache'))
    )
    with op.batch_alter_table('provider_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_cache_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ad_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=False),
    sa.Column('login_customer_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('time_zone', sa.String(length=64), nullable=True),
    sa.Column('is_test_account', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['ad_connections.id'], name=op.f('fk_ad_accounts_connection_id_ad_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_accounts')),
    sa.UniqueConstraint('workspace_id', 'provider', 'external_id', name=op.f('uq_ad_accounts_workspace_id_provider_external_id'))
    )
    with op.batch_alter_table('ad_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_accounts_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_accounts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_accounts_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('plan_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=False),
    sa.Column('approved_by_name', sa.String(length=120), nullable=False),
    sa.Column('financial_confirmation', sa.Boolean(), nullable=False),
    sa.Column('policy_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('consumed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_approvals_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_plan_id'), ['plan_id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('before_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('after_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_executions_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions')),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name=op.f('uq_executions_organization_id_idempotency_key'))
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invitations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitations_token_hash'))
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_organization_id'), ['organization_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'organization_id', name=op.f('uq_memberships_user_id_organization_id'))
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('plan_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_revisions_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_revisions')),
    sa.UniqueConstraint('plan_id', 'version', name=op.f('uq_plan_revisions_plan_id_version'))
    )
    with op.batch_alter_table('plan_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_revisions_plan_id'), ['plan_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('daily_budget_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workspaces_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_organization_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('plan_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_revisions_plan_id'))

    op.drop_table('plan_revisions')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_organization_id'))

    op.drop_table('invitations')
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_executions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_executions_organization_id'))

    op.drop_table('executions')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_plan_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('ad_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_accounts_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_ad_accounts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ad_accounts_connection_id'))

    op.drop_table('ad_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('provider_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_cache_organization_id'))

    op.drop_table('provider_cache')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_plans_organization_id'))

    op.drop_table('plans')
    op.drop_table('organizations')
    op.drop_table('oauth_states')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_after'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))

    op.drop_table('audit_events')
    op.drop_table('api_usage')
    with op.batch_alter_table('ad_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_connections_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_ad_connections_organization_id'))

    op.drop_table('ad_connections')
    # ### end Alembic commands ###
